version: "3"

services:
  soccer-hadoop:
    build:
      context: .
      dockerfile: soccer-hadoop/Dockerfile
      args:
        - PARENT_FOLDER=soccer-hadoop
    container_name: soccer_hadoop_container
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
      - "8088:8088"
      - "50070:50070"
    volumes:
      - soccer_hadoop_vol:/hadoop/data
    environment:
      - CLUSTER_NAME=soccerball_hadoop

  soccer-kafka:
    build:
      context: .
      dockerfile: soccer-kafka/Dockerfile
    container_name: soccer_kafka_container
    ports:
      - "9092:9092"
    volumes:
      - soccer_kafka_vol:/kafka_data
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=soccer-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - soccer-zookeeper

  soccer-zookeeper:
    image: bitnami/zookeeper:3.7
    container_name: soccer_zookeeper_container
    ports:
      - "2181:2181"
    volumes:
      - soccer_zookeeper_vol:/kafka_data
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  soccer-spark:
    build:
      context: .
      dockerfile: soccer-spark/Dockerfile
    container_name: soccer_spark_container
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - soccer_spark_vol:/spark/data
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"

  soccer-spark-worker:
    image: bitnami/spark:3.2.0
    container_name: soccer_spark_worker_container
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://soccer-spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - soccer_spark_vol:/spark/data

volumes:
  soccer_hadoop_vol:
  soccer_spark_vol:
  soccer_zookeeper_vol:
    driver: local
  soccer_kafka_vol:
    driver: local
